on:
  push:
    branches:
      - "main"
    tags:
      - "*"
  pull_request:
    branches:
      - "develop"
  schedule:
    - cron: "0 0 1 */2 *"
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Event
        run: echo "Triggered by $GITHUB_EVENT_NAME"
      - 
        name: Say Hello
        run: echo "Hello world!"
